const constants = {
  NAVIGATE_TO: "NAVIGATE_TO",
  START_FETCHING: "START_FETCHING",
  GET_MOVIES: "GET_MOVIES",
  SAVE_MOVIE: "SAVE_MOVIE",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  UPDATE_SEARCH_INPUT: "UPDATE_SEARCH_INPUT",
  UPDATE_PAGE_NUMBER: "UPDATE_PAGE_NUMBER",
}

export default constants